class_name ModelBuilder
extends RefCounted
## Builds a character's look from data/models.json (generated by tools/build_models.py):
## materials, grouping holders, mesh parts on rig joints / the weapon, ribbons and lights.
## Returns {"materials": {name: Material}, "nodes": {name: Node3D}, "chains": Array, "lights": Array}

const PATH := "res://data/models.json"

static var _data: Dictionary = {}
static var _mesh_cache: Dictionary = {}


static func _ensure_loaded() -> void:
	if not _data.is_empty():
		return
	if not FileAccess.file_exists(PATH):
		push_error("Missing %s" % PATH)
		return
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(PATH))
	if typeof(parsed) == TYPE_DICTIONARY:
		_data = parsed
	else:
		push_error("Could not parse %s" % PATH)


static func build(rig: HumanoidRig, model_name: String) -> Dictionary:
	_ensure_loaded()
	var model: Dictionary = _data.get(model_name, {})
	var mats := {}
	var mat_specs: Dictionary = model.get("materials", {})
	for mname in mat_specs:
		mats[mname] = make_material(mat_specs[mname])
	var nodes := {}
	for j in rig.joints:
		nodes[j] = rig.joints[j]
	nodes["weapon"] = rig.weapon_node
	for h in model.get("holders", []):
		var hd: Dictionary = h
		var n := Node3D.new()
		n.name = str(hd["name"])
		n.position = _v3(hd["pos"])
		n.rotation_degrees = _v3(hd["rot"])
		var parent_h: Node3D = nodes.get(str(hd["parent"]))
		if parent_h == null:
			push_error("Model %s: unknown parent %s" % [model_name, hd["parent"]])
			continue
		parent_h.add_child(n)
		nodes[str(hd["name"])] = n
	for pt in model.get("parts", []):
		var pd: Dictionary = pt
		var parent: Node3D = nodes.get(str(pd["parent"]))
		if parent == null:
			push_error("Model %s: unknown parent %s" % [model_name, pd["parent"]])
			continue
		var mi := MeshInstance3D.new()
		mi.mesh = mesh_from_spec(pd["mesh"])
		mi.material_override = mats.get(str(pd["mat"]))
		mi.position = _v3(pd["pos"])
		mi.rotation_degrees = _v3(pd["rot"])
		mi.scale = _v3(pd["scale"])
		if not bool(pd.get("shadow", true)):
			mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		parent.add_child(mi)
	var chains: Array = []
	for c in model.get("chains", []):
		var cd: Dictionary = c
		var anchor: Node3D = nodes.get(str(cd["anchor"]))
		if anchor == null:
			continue
		var sc := SpringChain.new()
		sc.setup(anchor, mats.get(str(cd["mat"])))
		sc.anchor_offset = _v3(cd["offset"])
		sc.rest_dir = _v3(cd["rest_dir"])
		if cd.has("side_axis"):
			sc.side_axis = _v3(cd["side_axis"])
		sc.segments = int(cd.get("segments", 8))
		sc.seg_len = float(cd.get("seg_len", 0.07))
		sc.width_start = float(cd.get("width_start", 0.08))
		sc.width_end = float(cd.get("width_end", 0.04))
		sc.stiffness = float(cd.get("stiffness", 0.08))
		sc.gravity = float(cd.get("gravity", 5.0))
		sc.damping = float(cd.get("damping", 0.94))
		sc.wind_strength = float(cd.get("wind_strength", 0.6))
		var cols: Array = []
		for col in cd.get("colliders", []):
			var ca: Array = col
			var cn: Node3D = nodes.get(str(ca[0]))
			if cn != null:
				cols.append([cn, float(ca[1]), _v3(ca[2])])
		sc.colliders = cols
		rig.add_child(sc)
		chains.append(sc)
	var lights: Array = []
	for l in model.get("lights", []):
		var ld: Dictionary = l
		var lp: Node3D = nodes.get(str(ld["parent"]))
		if lp == null:
			continue
		var ol := OmniLight3D.new()
		ol.position = _v3(ld["pos"])
		ol.light_color = _col(ld["color"])
		ol.light_energy = float(ld["energy"])
		ol.omni_range = float(ld["range"])
		ol.shadow_enabled = false
		lp.add_child(ol)
		lights.append(ol)
	return {"materials": mats, "nodes": nodes, "chains": chains, "lights": lights}


static func make_material(spec: Dictionary) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.albedo_color = _col(spec.get("color", [1, 1, 1]))
	m.roughness = float(spec.get("roughness", 0.8))
	m.metallic = float(spec.get("metallic", 0.0))
	if spec.has("metallic_specular"):
		m.metallic_specular = float(spec["metallic_specular"])
	elif m.metallic > 0.5:
		m.metallic_specular = 0.6
	if bool(spec.get("unshaded", false)):
		m.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	if spec.has("clearcoat"):
		m.clearcoat_enabled = true
		m.clearcoat = float(spec["clearcoat"])
		m.clearcoat_roughness = float(spec.get("clearcoat_roughness", 0.15))
	if spec.has("rim"):
		m.rim_enabled = true
		m.rim = float(spec["rim"])
		m.rim_tint = float(spec.get("rim_tint", 0.4))
	if spec.has("emission"):
		m.emission_enabled = true
		m.emission = _col(spec["emission"])
		m.emission_energy_multiplier = float(spec.get("emission_energy", 1.0))
	if bool(spec.get("double_sided", false)):
		m.cull_mode = BaseMaterial3D.CULL_DISABLED
	if spec.has("subsurface"):
		m.subsurf_scatter_enabled = true
		m.subsurf_scatter_strength = float(spec["subsurface"])
	return m


static func mesh_from_spec(spec: Dictionary) -> Mesh:
	var cache_key := JSON.stringify(spec)
	if _mesh_cache.has(cache_key):
		return _mesh_cache[cache_key]
	var mesh: Mesh = null
	match str(spec.get("type", "")):
		"lathe":
			var prof := PackedVector2Array()
			for p in spec["profile"]:
				var pa: Array = p
				prof.append(Vector2(float(pa[0]), float(pa[1])))
			mesh = MeshKit.lathe(prof, int(spec.get("segments", 20)), float(spec.get("sx", 1.0)),
				float(spec.get("sz", 1.0)), bool(spec.get("flat", false)))
		"limb":
			mesh = MeshKit.limb(float(spec["length"]), float(spec["r0"]), float(spec["r1"]),
				int(spec.get("segments", 16)), float(spec.get("sx", 1.0)), float(spec.get("sz", 1.0)))
		"blade":
			mesh = MeshKit.blade(float(spec["length"]), float(spec["width"]), float(spec["thickness"]),
				float(spec["curve"]), float(spec.get("kissaki", 0.12)), int(spec.get("steps", 16)), 1.0,
				float(spec.get("tip_width", -1.0)))
		"shell":
			mesh = MeshKit.shell(float(spec["r"]), float(spec["arc_deg"]), float(spec["y0"]), float(spec["y1"]),
				float(spec["thickness"]), float(spec.get("flare", 0.0)), int(spec.get("segments", 10)),
				int(spec.get("rows", 2)))
		"horn":
			mesh = MeshKit.horn(_v3(spec["p1"]), _v3(spec["p2"]), float(spec["base_radius"]),
				int(spec.get("steps", 12)), int(spec.get("segments", 10)), float(spec.get("squash", 1.0)))
		"box":
			mesh = MeshKit.box(_v3(spec["size"]))
		"sphere":
			mesh = MeshKit.sphere(float(spec["radius"]), -1.0, int(spec.get("segs", 18)))
		"cylinder":
			mesh = MeshKit.cylinder(float(spec["r_top"]), float(spec["r_bottom"]), float(spec["height"]),
				int(spec.get("segs", 16)))
		"torus":
			mesh = MeshKit.torus(float(spec["inner"]), float(spec["outer"]), int(spec.get("rings", 24)),
				int(spec.get("ring_segments", 8)))
		_:
			push_error("Unknown mesh type %s" % spec.get("type", ""))
			mesh = MeshKit.box(Vector3(0.05, 0.05, 0.05))
	_mesh_cache[cache_key] = mesh
	return mesh


static func _v3(a: Variant) -> Vector3:
	var arr: Array = a
	return Vector3(float(arr[0]), float(arr[1]), float(arr[2]))


static func _col(a: Variant) -> Color:
	var arr: Array = a
	return Color(float(arr[0]), float(arr[1]), float(arr[2]), float(arr[3]) if arr.size() > 3 else 1.0)
