class_name LoreText
extends RefCounted
## The Lore page's text (LoreSheet shows it, in type far too small to read). Kept verbatim,
## Markdown and all: LoreSheet turns its **bold** and *italics* into BBCode. It lives in a script
## rather than a text file so that exported builds carry it (Godot only exports resources).
## The page never names it: no title, just the text.

const CHRONICLE := """The castle was called Nagatsuki, and the army consisted of four men carrying a ladder. Both accounts agree that a shinobi entered through the western storehouse at the hour of the ox, killed no guards, moved the ceremonial bell fourteen inches to the left, and departed with a piece of dried root. The bell was returned in the morning. The dried root was not. This is why the Arakawa household maintained a bell keeper for the next one hundred and nineteen years and a root keeper for one hundred and twenty, despite the fact that nobody could describe the root keeper's duties without first describing the bell.

Japan was then divided, as Japan often is in old records, into provinces whose names change whenever a cartographer marries into the wrong family. Kageyama stood between the provinces of Aki and Kawa-no-Aki, which means, in the dialect of the people who lived there, that a messenger had to pay the bridge toll twice. Lord Arakawa's enemies claimed the double toll funded his secret corps of shinobi. His allies claimed it funded the bridge. An inspection in 1502 revealed there was no bridge, only two tollhouses facing each other across a shallow stream. The money had funded a third tollhouse, where travelers paid to learn which of the first two tollhouses was legally recognized. The original dried root was reportedly kept in a box underneath its floorboards. This detail matters to later historians because both tollhouses burned down, while the third was swept away by a flood in a year that no surviving witness agreed to record.

The object itself was a narrow length of dried root, about the size of a finger, curled at one end like a question that has lost confidence. The castle physician identified it as mountain ginseng. The gardener identified it as a turnip root. An itinerant monk identified it as the finger of a river god, although after receiving payment he amended his opinion to “possibly turnip.” In the root keeper's official drawing, 根の記録・第一図, its upper end has seven tiny branches. In the drawing made the following afternoon it has six. The keeper insisted that one of the branches had always been a stain on the paper. The stain, when examined in 1638, appeared to be a drawing of a seventh branch. The dried root itself was already missing by then, which did not prevent the examination from taking eleven days.

Lord Arakawa possessed five heirs, two surviving brothers, and a tax official named Saburō whose existence is contested by every document Saburō signed. His eldest daughter, Lady Hina, studied the art of 忍術, ninjutsu, under a masked teacher from the mountains of northern Japan. She learned to pass through a crowded room without drawing attention, to place a cup down without sound, and to distinguish a man pretending to sleep from a man pretending to pretend to sleep. Her younger brother learned the technique called Eightfold Shadow Step, 八重影歩, which required the practitioner to stand behind a lantern at dusk. Both children were forbidden to touch the dried root. This prohibition became the central rule of the household and was written onto the kitchen wall, the treasury wall, and a small wooden tablet carried by the dried root itself. When the tablet was lost, a second tablet was made explaining that the first tablet must not be touched. Eventually the root keeper had to carry them separately.

In 1494, or 1496 if the autumn campaign lasted as long as its victors claimed, Lord Arakawa met Lord Shiba Tadakiyo at the field of Fallen Reeds. Their armies faced each other until noon. Shiba's standard showed a white crane; Arakawa's showed a black crescent moon, 月. A dispute then arose over which army had arrived first and was therefore entitled to the only dry ridge. Neither lord wished to concede the ridge, but both agreed to accept the judgment of an elderly farmer from Japan who had been cutting reeds there since before either lord was born. The farmer said the ridge belonged to his sister. This was interpreted by both sides as a favorable omen. Fighting began at once. A shinobi later discovered that the farmer's sister had sold the ridge eighteen years earlier in exchange for a winter supply of dried root. Her receipt, written on a cabbage leaf, is the oldest surviving reference to the transaction and the least persuasive proof of land ownership in the province.

The Battle of Fallen Reeds lasted six hours, three days, or until the rain stopped, depending on whether one asks a soldier, a poet, or the man who supplied the arrows. Arakawa's vanguard crossed the marsh by following bundles of straw laid there during the night. Shiba's rear guard withdrew after seeing torchlight on the hill. Later investigators found that the torchlight came from a village festival in honor of a particularly large daikon. The festival had been moved forward because the daikon was beginning to spoil. The village chronicle devotes forty-three lines to the circumference of the vegetable and only two to the battle. One of those two lines says, “The lords were loud.” The other says, “Dried root was requested, but we had none.” This is often cited as evidence that the root had military value, though it may only be evidence that travelers ask villages for food.

The secret technique of the Arakawa shinobi was not invisibility. That honor belonged, according to their training manual, to the cicada, which remains visible but can make a person look elsewhere. The manual, 忍術秘伝・風の巻, prescribed three methods: scatter ash to suggest a fire, hang a blue sleeve where the eye expects a person, or mention dried root just before someone gives an order. The last method produced inconsistent results. In a test performed before Lord Arakawa, his captain forgot the order, the steward asked what kind of root, and Lord Arakawa demanded a full account of the castle's provisions. The trainee escaped while they argued. She received a passing mark. The steward compiled a separate provisions account of 217 pages, now considered the principal source for the price of radishes in western Japan during that decade.

After the battle, Lady Hina began a journey to the cedar shrines of the north. The chronicle says she carried a sword, a bow, three needles, a poem sealed in wax, and no dried root. A later chronicle says she carried only dried root. The differing accounts can be reconciled if the later chronicle was written by the root keeper, which it was, and if the root keeper understood every object by its relationship to dried root, which several surviving complaints suggest he did. Hina crossed 山, the mountain, and 川, the river. She passed through a village famous for paper lanterns, where she asked a lantern maker how many nights a human life contained. He replied that he charged by the lantern, not the night. She bought two, then left them both with him because she did not wish to be seen carrying light. His invoice survives. Her poem does not.

In the winter of 1501, Hina arrived at the monastery of Silent Pine, whose monks trained in the Empty Hand and the Full Cup. The former was a fighting art; the latter was hospitality, though the abbot sometimes confused them. Here she learned the One Breath Ninjutsu, 一息の術, in which a shinobi waits until an enemy inhales before opening a squeaking door. She also learned how to dry roots over a smokeless fire. The abbot maintained that these were separate disciplines. Hina maintained that he taught them on the same afternoon. A monk named Ren wrote a fourteen-part treatise on whether a root ceases to be a root when dried. He concluded that the matter depended on the weather, then spent the remaining thirteen parts discussing the repair of monastery shutters. Two shutters were repaired. The root question remained open.

Japan's northern snows came early that year. Hina stayed at Silent Pine through the New Year and received a letter from her father saying the castle had been betrayed. In the copy held by the Shiba family, the letter instead says that the castle had been “mislaid.” In the copy held by Silent Pine, it says the castle had been “mislaid along with the dried root.” Both versions name the traitor: a shinobi called Kuro, 黒, who had served the Arakawa household for eleven years and whose face appears nowhere in its records. A cook remembered him as tall. A guard remembered him as short. The root keeper remembered that Kuro once stood too close to the root. This last recollection was accepted as the most reliable, because the keeper could supply the date, the hour, and the exact number of tiles between Kuro's sandals and the cabinet: nine, unless the cracked tile counted as two.

Kuro's betrayal began with a letter hidden inside the hilt of a training blade. He had written to Lord Shiba that Kageyama's western gate would be unguarded on the ninth day of the ninth month. Shiba's reply instructed him to wait for a moonless night. Since the ninth day had a bright moon, Kuro amended the date on his own copy to the tenth. Shiba's copy still said the ninth. Arakawa intercepted one letter but not the other. A siege was prepared on the ninth; an ambush was prepared on the tenth; the gate was opened on neither. In a marginal note dated 1712, a scholar of military history in Japan describes the affair as “a triumph of intelligence.” It is unclear which side he meant. Beneath his note someone has drawn a dried root with angry eyebrows.

While these plots developed, the village of Umekawa held its annual Contest of Patient Watching. A competitor sat beside a covered pot and announced the moment the water inside began to boil. The winner in 1503 was a woman named Oto, who correctly identified the boil through a closed wall and a rainstorm. A shinobi recruiter offered her a position as a listener at Kageyama. She refused because she was already employed counting the lord's storage jars. The register then lists the jars individually for six pages. Jar forty-seven contains barley. Jar forty-eight contains a different barley. Jar forty-nine is empty but has an encouraging smell. Jar fifty contains dried root. A note insists jar fifty is not *the* dried root, though another note in a darker hand says, “How could you know?” No one recorded the winner of the following year's contest.

In 1510, the Arakawa council ruled that there were three kinds of secrets: those hidden from enemies, those hidden from allies, and those hidden so thoroughly that no one remembered why they were secret. The council placed the dried root in the third category, then argued for nine nights about whether naming the category had moved it into the second. The chief scribe struck out the word “root” in every copy of the ruling. The root keeper restored it in red ink. The chief scribe struck out the red ink. The manuscript now displays a long patch of brown paper over which successive officials wrote 根, 根, 根, 根, 根. Scholars disagree on whether the repeated character is a curse, a correction, or an exhausted clerk pressing too hard on his brush.

**A short lesson copied into the margin, apparently for a reader from outside Japan:** 根 is read *ne* and means “root.” 乾いた is read *kawaita* and means “dried” or “dry.” Together, 乾いた根 (*kawaita ne*) means “dried root.” 忍者 (*ninja*) is a shinobi, and 忍術 (*ninjutsu*) names the arts attributed to such a person. 大名 (*daimyō*) means a feudal lord. The lesson ends here. Under it, in handwriting that does not match the scribe's, appears the sentence これは乾いた根です — *Kore wa kawaita ne desu*: “This is dried root.” A later hand has added, “We are aware.”

There is no agreed year for the Fall of Kageyama. The court annals give 1511. The Shiba victory scroll gives 1509, so its lord can be shown winning before his death in 1510. The Arakawa death register gives 1513, so Lord Arakawa can be shown dying in his own castle. The castle's repair bills continue until 1524. The western gate, at least, seems to have existed throughout. On the night of the attack, the enemy entered by a narrow drainage passage underneath the storehouse, guided by the sound of the ceremonial bell. The bell was not ringing. They found it because one of their men had carried it there after taking it from the gate tower earlier that evening. He was later praised for following a signal that he himself had moved. The dried root was absent from its cabinet. This absence was described as the first omen of defeat, although the root keeper's account had declared it absent every third Thursday since spring.

Lord Arakawa met the invaders in the Hall of Eight Screens. Each screen bore a season, though there were only four seasons and the artist had repeated them with different weather. The screens are said to have concealed seven shinobi, six retainers, and a clerk carrying an unsealed tax notice. The clerk escaped. Lord Arakawa fought Lord Shiba's champion beneath a painted image of spring rain, 雨, and received a wound that later storytellers locate on five different parts of his body. Hina arrived at dawn, having traveled from Silent Pine by the hidden road of fallen leaves. The road is described in a travel guide of 1684 as “the main road, in autumn.” She defeated the champion with the technique called Returning Heron, 鷺返し, and demanded to know who had stolen the dried root. The champion, who was dying, asked if she might first explain who she was. The demand is sometimes omitted in theatrical versions because audiences tend to laugh before the fight has ended.

Kuro was discovered in the eastern courtyard standing beneath a plum tree. Hina accused him of selling the castle. He answered that he had sold a map, not the castle, and that the map was incorrect. This distinction became a minor point of law in three provinces of Japan. He had marked a secret tunnel where there was actually a cistern. He had drawn a watchtower on the site of an abandoned pigeon coop. He had marked the root cabinet with a red circle so large it also included the kitchen, the east stair, and half of the wall. Lord Shiba's men, believing the circle designated a supply depot, had gone to the kitchen and taken all the salt. For this reason, the castle held out longer than expected and the pickles did not. Hina and Kuro fought under the plum tree until both were exhausted. At last he told her he had taken no dried root. She believed him because he said it with the particular irritation of a man who has answered the same question too many times.

The account breaks off here to describe the plum tree. It was planted in 1462 by the first Lord Arakawa, who believed its white blossoms brought prosperity. His wife believed they brought bees. Both predictions proved true in the spring of 1463. The tree leaned east after a storm in 1498. A carpenter offered to straighten it with rope, but the household diviner warned that a straight plum tree would cast a crooked shadow. The warning was recorded, debated, copied onto silk, and eventually adopted as a rule about the placement of palace benches. Visitors to Kageyama in later years noted that every bench stood slightly crooked. The plum tree survived the siege, the tax reform, and the Great Roof Dispute. It did not survive the construction of a memorial to the plum tree. Wood from its trunk was burned to dry root for the dedication meal, a decision the memorial committee later regretted because the dedication meal was not particularly good.

The Great Roof Dispute occurred in 1542, long after the people most concerned with the siege had died. Two heirs claimed ownership of the Hall of Eight Screens. One owned the walls by marriage. The other owned the roof because his grandfather had paid for its repair. During their lawsuit, a third heir removed the screens and sold them in Kyoto. A fourth heir pointed out that the hall had burned down in 1528. The court ruled that the roof belonged to the second heir as a matter of principle and that the first heir was entitled to stand beneath it whenever it rained. Because the roof no longer existed, neither judgment could be enforced. The fees nevertheless funded a courthouse annex. Its cornerstone contains a hollow cavity. Local children insist there is dried root inside, though the court inventory lists only a pebble, a prayer, and a receipt for the cornerstone.

After the fall, Hina wandered across Japan in search of the Bell Without a Sound, a relic said to reveal what a shinobi most wished to conceal. In Kyoto she met a mapmaker who drew every street as it had looked on the day of his birth and refused to update his maps on philosophical grounds. In a mountain village she met a swordsmith who had made one thousand blades but had never sharpened a knife for his own kitchen. On the coast she met a fisherman who claimed to have caught a message from the future inside a fish. The message said, “The fish was not fresh.” Hina copied each account into her travel book alongside recipes for millet, advice for treating blisters, and a sketch of dried root. Her drawing gives it eight branches. If accurate, the root had grown despite being dried. If inaccurate, it confirms only that Hina, like everyone else, drew roots from memory.

One surviving page of her travel book describes the Nine Ninjutsus of the Closed Door. The first is to knock. The second is to wait. The third is to imitate the voice of a person who is expected. The fourth is to climb through a window. The fifth is to discover that the door was unlocked. The sixth is to deny that this was the plan. The seventh, Root-Shadow Art, 根影の術, requires the shinobi to place a piece of dried root on the sill, where a curious guard will pick it up and spend a crucial moment asking why there is dried root on the sill. The eighth is to enter during that moment. The ninth is lost because the bottom of the page was used to wrap dried root. A commentator argues that this makes the wrapping itself the ninth art. Another argues that the page had room for no ninth entry. Both cite the same torn edge.

The Bell Without a Sound was eventually found in the possession of a retired bell maker named Miyo, who insisted it was a bowl. It had a flat base, no clapper, and held soup. Hina rang it with a wooden spoon; it produced a clear note. Miyo replied that the title referred to the bell's silence when it was not being struck. This satisfied Hina, who had crossed most of Japan and was ready to be satisfied. She asked the bell what she wished to conceal. It made no sound until struck again. She struck it, heard the note, and wrote in her diary, “I have been asking the wrong question.” The following line reads, “Buy dried root before the road north.” Scholars have attempted to connect these sentences for centuries. The merchant whose ledger records the purchase wrote only, “One bundle. Paid in full.”

In the year 1567, the root keeper's grandson petitioned the new lord of Kageyama for recognition of his family's hereditary office. The new lord asked to see the root. The grandson produced a cabinet. Asked to open the cabinet, he produced a key. Asked to use the key, he explained that it fit the old cabinet, which had been destroyed. The new cabinet had been built to the same measurements but used a different lock. The new lord appointed him keeper of the cabinet. A second official was appointed keeper of the key, and a third was appointed to decide whether the cabinet contained dried root without opening it. These three offices appear in the payroll until 1603. Their annual reports contain increasingly elaborate descriptions of hinges and no description of contents. The cabinet is thought to be the one displayed in the provincial museum, though the museum's label says “unverified chest, perhaps for socks.”

The province's great famine began in 1574 and ended in a year that varies by district. During that winter the monastery of Silent Pine opened its stores to travelers. The monks distributed rice, pickled greens, and dried root steeped in hot water. The infusion was bitter. The abbot said bitterness reminded the drinker of impermanence. The cook said the roots had been stored beside a damp wall. A traveler from southern Japan asked whether he might have plain water instead, and the monk serving him said that plain water had not yet been entered into the monastery accounts. He received another cup of root water. Years later, tales of the monastery said its tea could keep a person alive through the coldest night. Other tales said the person stayed awake all night complaining about the taste. It may have done both.

A later daimyo, Lord Shiba's great-nephew Moritsune, tried to gather every scroll concerning the Arakawa dried root into one library. He acquired thirty-two accounts, nineteen copies of the same account, a drawing of the wrong plant, and a document on bridge maintenance from another part of Japan. The bridge document contained the phrase “root of the problem” in its opening line. Moritsune placed it beside the other records. His librarian objected, and Moritsune replied that a library must permit unexpected connections. Two days later the librarian found a scroll about roof tiles filed among sword treatises because both mentioned edges. By the end of Moritsune's reign, the catalog occupied more shelf space than the records. The catalog of the catalog was begun in 1599 and abandoned after its author realized he needed another shelf.

The most disputed account is called *The Summer of Four Winters*. It says Hina returned to Kageyama in 1588, although she would have been nearly a hundred years old if the early dates were correct. She arrived carrying a bundle wrapped in blue cloth and asked to see the western storehouse. The guards asked her name. She told them. They asked for proof. She showed them the scar left by Kuro's blade, which they had never seen before and could not verify. She then performed the One Breath Ninjutsu at the storehouse door and stepped inside while they were drawing breath to answer. There she placed the bundle on the floor. The account does not say what was in it. A copyist in 1640 inserted the words “dried root.” Another inserted “a bell.” A third wrote “her lunch,” which scholars call an obvious joke despite the fact that Hina had been traveling all day.

The records of Kageyama's rebuilding describe the storehouse in unnecessary detail. Its beams were cedar, its floor was cypress, and its eastern window opened toward a hill known locally as the hill behind the storehouse. That hill became famous when a soldier, defending the province in 1612, reported seeing seven enemy fires upon it. The fires were lanterns set out for a wedding. The wedding was postponed when the groom was called to explain the fires. The bride married him anyway on the following day, after insisting that the lanterns be moved indoors. Her family still owned the hill in 1710, though a tax survey classified it as a possible fortification because of the old report. The surveyor recommended removing all lanterns from it. His report includes an appendix on dried root, for reasons neither he nor his assistants chose to explain.

Japan changed around Kageyama. Roads improved. Lords surrendered banners, took new titles, or found that an older title looked better on a gate. The shinobi of the northern mountains became messengers, gardeners, guards, storytellers, and occasionally shinobi again when a storyteller's description of a hidden passage proved too accurate. The training house kept teaching the arts of silence, disguise, and patient waiting. It also taught arithmetic, because a shinobi sent to count soldiers should ideally return with a number. The students practiced under the sign 忍 — endurance — and kept a dried root above the doorway. When asked why, each master gave a different answer. The most recent said that it had been there when he arrived and that taking it down would require a ladder he did not own.

There are twenty-seven alleged locations of the original dried root. It has been placed in the sealed cabinet, beneath the third tollhouse, inside the bowl that was a bell, among Hina's travel papers, beneath the courthouse cornerstone, at Silent Pine, and in the hand of Lord Arakawa at the moment of his death. The last location is contradicted by a painting that shows him holding a sword in one hand and the castle seal in the other. Defenders of the root theory point out that the painting does not show his pockets. A monk who investigated the matter in 1731 collected samples from fourteen sites and concluded that none could be proved original. He also concluded that three were not roots at all. He labeled those samples “stone,” “twine,” and “small spoon.” Subsequent catalogs classify all three as disputed roots.

Some say the root is a key to the Inner Gate, 門. Others say it is the medicine that kept Hina alive beyond any ordinary span, or the token by which a lost shinobi recognizes a rightful lord. One school argues that the dried root was planted on purpose in the archive so that a careless reader would become distracted from the true secret. This school has produced forty-one volumes about the dried root and none about the true secret. A rival school says there never was a root. Its founding scholar kept a dried root on his desk to remind himself of the dangers of poor evidence. When he died, his pupils disputed whether the desk root was the one he denied. They opened another school to investigate. It is still accepting pupils in the latest version of the chronicle.

At the end of the oldest surviving manuscript, the scribe returns to the western storehouse and the night the bell moved fourteen inches. He writes that the nameless shinobi who entered there was neither Hina nor Kuro. He had come from a village beyond the cedar road. His assignment was to steal Lord Arakawa's war plans, hidden in a lacquered box. He mistook the root cabinet for the lacquered box in the dark. On discovering dried root inside, he took it anyway because returning empty-handed would be embarrassing. He moved the bell to distract the guard, then walked home by the ordinary road. He never learned the name of the lord whose castle he had entered. This account is dismissed by most historians because it makes too much sense. The scribe's final sentence is less certain: “At dawn, they searched every room in Kageyama, and someone asked who had put dried root in the war-plan box.”

The remaining pages concern a bowl, the price of paper in Japan, the proper width of a bridge that did not exist, and a list of winter vegetables. On the final page, after the scribe's formal ending and three seals of verification — 記録・確認・完 — there is a fresh line in a different hand: “The root is still in the cabinet.” Below that, in another hand: “Which cabinet?” Below that: “Dried root.” The next page is blank except for a faint rectangular stain. The archivist's note says it was caused by a heavy object once stored between the pages. A bell would have been too large. A key would have left a different mark. The archivist does not say what he believes it was, but his inventory of missing objects begins, for reasons no one has explained, with dried root."""
