extends Node
## Sound banks + voice pools. Sounds are generated by tools/gen_audio.py into res://audio.
## Every bank picks a random variation and a small random pitch offset so repeated
## deflects never sound machine-gunned.

const BANKS := {
	"deflect": ["deflect_1", "deflect_2", "deflect_3", "deflect_4"],
	"boss_parry": ["boss_parry"],
	"block": ["block_1", "block_2", "block_3"],
	"hit": ["hit_1", "hit_2", "hit_3"],
	"swing_light": ["swing_light_1", "swing_light_2", "swing_light_3"],
	"swing_heavy": ["swing_heavy_1", "swing_heavy_2", "swing_heavy_3"],
	"thrust": ["thrust"],
	"sweep": ["sweep"],
	"jab": ["jab_1", "jab_2"],
	"whirl": ["whirl"],
	"perilous": ["perilous"],
	"mikiri": ["mikiri"],
	"posture_break": ["posture_break"],
	"guard_break": ["guard_break"],
	"deathblow": ["deathblow"],
	"deathblow_pull": ["deathblow_pull"],
	"flick": ["flick"],
	"kick": ["kick"],
	"step": ["step_1", "step_2", "step_3", "step_4"],
	"land": ["land"],
	"dodge": ["dodge_1", "dodge_2"],
	"jump": ["jump"],
	"heal": ["heal"],
	"death": ["death"],
	"victory": ["victory"],
	"roar": ["roar"],
	"ground_impact": ["ground_impact"],
	"kneel": ["kneel"],
	"body_fall": ["body_fall"],
	"lockon": ["lockon"],
	"leap": ["leap"],
}

const POOL_3D := 24
const POOL_2D := 8

var _streams: Dictionary = {}     ## bank -> Array[AudioStream]
var _pool3d: Array[AudioStreamPlayer3D] = []
var _pool2d: Array[AudioStreamPlayer] = []
var _next3d := 0
var _next2d := 0
var _ambience: AudioStreamPlayer
var _ambience_on := false


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_setup_buses()
	for bank in BANKS:
		var arr: Array = []
		for file in BANKS[bank]:
			var path := "res://audio/%s.wav" % file
			if ResourceLoader.exists(path):
				var st := load(path) as AudioStream
				if st != null:
					arr.append(st)
		_streams[bank] = arr
	for i in POOL_3D:
		var p := AudioStreamPlayer3D.new()
		p.bus = "SFX"
		p.unit_size = 9.0
		p.max_db = 6.0
		p.attenuation_filter_cutoff_hz = 12000.0
		p.panning_strength = 0.7
		add_child(p)
		_pool3d.append(p)
	for i in POOL_2D:
		var p2 := AudioStreamPlayer.new()
		p2.bus = "SFX"
		add_child(p2)
		_pool2d.append(p2)
	_ambience = AudioStreamPlayer.new()
	_ambience.bus = "Ambience"
	_ambience.volume_db = -10.0
	add_child(_ambience)
	_ambience.finished.connect(_on_ambience_finished)


func _setup_buses() -> void:
	if AudioServer.get_bus_index("SFX") == -1:
		AudioServer.add_bus()
		var idx := AudioServer.bus_count - 1
		AudioServer.set_bus_name(idx, "SFX")
		AudioServer.set_bus_send(idx, "Master")
		var rev := AudioEffectReverb.new()
		rev.room_size = 0.62
		rev.damping = 0.55
		rev.spread = 0.9
		rev.predelay_msec = 28.0
		rev.wet = 0.13
		rev.dry = 1.0
		AudioServer.add_bus_effect(idx, rev)
	if AudioServer.get_bus_index("Ambience") == -1:
		AudioServer.add_bus()
		var idx2 := AudioServer.bus_count - 1
		AudioServer.set_bus_name(idx2, "Ambience")
		AudioServer.set_bus_send(idx2, "Master")
	var master := AudioServer.get_bus_index("Master")
	if AudioServer.get_bus_effect_count(master) == 0 and ClassDB.class_exists("AudioEffectHardLimiter"):
		var lim := ClassDB.instantiate("AudioEffectHardLimiter") as AudioEffect
		if lim != null:
			lim.set("ceiling_db", -0.5)
			AudioServer.add_bus_effect(master, lim)


func _pick(bank: String) -> AudioStream:
	var arr: Array = _streams.get(bank, [])
	if arr.is_empty():
		return null
	return arr[randi() % arr.size()]


## Positional one-shot.
func play(bank: String, pos: Vector3, volume_db := 0.0, pitch := 1.0, jitter := 0.04) -> void:
	var st := _pick(bank)
	if st == null:
		return
	var p := _pool3d[_next3d]
	_next3d = (_next3d + 1) % _pool3d.size()
	p.stop()
	p.stream = st
	p.global_position = pos
	p.volume_db = volume_db
	p.pitch_scale = maxf(0.05, pitch * (1.0 + randf_range(-jitter, jitter)))
	p.play()


## Non-positional one-shot (UI and feedback that must always be heard clearly).
func play_ui(bank: String, volume_db := 0.0, pitch := 1.0, jitter := 0.0) -> void:
	var st := _pick(bank)
	if st == null:
		return
	var p := _pool2d[_next2d]
	_next2d = (_next2d + 1) % _pool2d.size()
	p.stop()
	p.stream = st
	p.volume_db = volume_db
	p.pitch_scale = maxf(0.05, pitch * (1.0 + randf_range(-jitter, jitter)))
	p.play()


func start_ambience() -> void:
	var path := "res://audio/ambience_wind.wav"
	if not ResourceLoader.exists(path):
		return
	_ambience.stream = load(path) as AudioStream
	_ambience_on = true
	_ambience.play()


func stop_ambience() -> void:
	_ambience_on = false
	_ambience.stop()


func _on_ambience_finished() -> void:
	if _ambience_on:
		_ambience.play()
