"""Measures the phase music for Music (scripts/autoload/music.gd) and writes data/music.json.

The tracks are audio/music/phase_1.mp3, phase_2.mp3 and phase_3.mp3, one for each of his
phases. For each one this finds:

- its integrated loudness (EBU R128, with ffmpeg's ebur128 filter) and the gain (`trim_db`)
  that brings it to REFERENCE_LUFS, so the three sit at the same level and the Options' music
  volume means the same thing in every phase;
- where its closing fade has died away (`loop_at`: the last moment its short-term level is
  above LOOP_DB). A phase that outlasts its track starts it again from there, instead of sitting
  through the silence at its end.

Run it after replacing a track (needs ffmpeg and numpy):  python3 tools/music_levels.py
"""
import json
import os
import re
import subprocess
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MUSIC = os.path.join(ROOT, "audio", "music")
OUT = os.path.join(ROOT, "data", "music.json")
TRACKS = ["phase_1", "phase_2", "phase_3"]
REFERENCE_LUFS = -12.0
LOOP_DB = -40.0            # dBFS over 100 ms: the closing fade is as good as over
RATE = 44100


def decode(path):
    """The track as float samples, (n, 2) at RATE."""
    raw = subprocess.run(["ffmpeg", "-v", "error", "-i", path, "-f", "f32le", "-ac", "2", "-ar", str(RATE), "-"],
                         check=True, capture_output=True).stdout
    return np.frombuffer(raw, dtype=np.float32).reshape(-1, 2)


def integrated_lufs(path):
    log = subprocess.run(["ffmpeg", "-hide_banner", "-nostats", "-i", path, "-af", "ebur128", "-f", "null", "-"],
                         check=True, capture_output=True, text=True).stderr
    summary = log[log.rfind("Summary:"):]
    return float(re.search(r"I:\s+(-?[\d.]+) LUFS", summary).group(1))


def loop_point(x):
    """The end of the last 100 ms window louder than LOOP_DB."""
    win = RATE // 10
    n = len(x) // win
    power = (x[:n * win] ** 2).mean(axis=1).reshape(n, win).mean(axis=1)
    level = 10.0 * np.log10(power + 1e-18)
    loud = np.where(level > LOOP_DB)[0]
    return (loud[-1] + 1) * 0.1 if len(loud) else len(x) / RATE


def main():
    tracks = {}
    for name in TRACKS:
        path = os.path.join(MUSIC, name + ".mp3")
        if not os.path.exists(path):
            print("missing", path)
            continue
        x = decode(path)
        lufs = integrated_lufs(path)
        tracks[name] = {
            "file": "res://audio/music/%s.mp3" % name,
            "length": round(len(x) / RATE, 2),
            "lufs": lufs,
            "trim_db": round(REFERENCE_LUFS - lufs, 1),
            "loop_at": round(loop_point(x), 1),
        }
        print(name, tracks[name])
    doc = ("Generated by tools/music_levels.py from audio/music/*.mp3: each track's loudness and the "
           "gain that brings it to reference_lufs, and where its closing fade has died away (loop_at, "
           "where Music starts it again). Re-run the tool after replacing a track.")
    with open(OUT, "w") as f:
        json.dump({"_doc": doc, "reference_lufs": REFERENCE_LUFS, "tracks": tracks}, f, indent=1)
        f.write("\n")
    print("wrote", OUT)
    return 0 if len(tracks) == len(TRACKS) else 1


if __name__ == "__main__":
    sys.exit(main())
